### ISSUE TITLE
Unable to install subed package (NonGNU Elpa)

### ISSUE THREAD

**Issue by edgar-vincent** [radian-software/straight.el#1025]
Running `(straight-use-package subed)`  (in a clean `init.el`) yields the following error:
`error("Invalid :files directive: %S" "LICENSES/GPL-3.0-or-later.txt")`

The error does not occur with `(straight-use-package '(subed :type git :host github :repo "sachac/subed" :files ("subed/*.el")))`.

Thanks a lot!

### Version information

* Emacs version: 28.2
* Operating system: Arch Linux

**Comment by progfolio** [comment]
Thank you for the bug report.
The reason this is failing is NonGNU ELPA apparently allows it's `:ignored-files` keyword to accept a list of strings or a string. We were only accounting for the list.

I've fixed this in #1026.

**Comment by progfolio** [comment]
This should now be fixed on the "develop" branch.
Testing is appreciated. Thanks again.

**Comment by edgar-vincent** [comment]
Thank you very much for having had a look at this.

I still get the same error with the following `init.el` file:
```
(setq straight-repository-branch "develop") 
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; Install subed
(straight-use-package 'subed)
```

Maybe I am not doing this properly. Please excuse me if it is the case.

**Comment by progfolio** [comment]
What is the output of `M-x straight-version`?

**Comment by edgar-vincent** [comment]
Whoops, sorry about that, I had to delete the `straight` directory in order for it to bootstrap the version from the `develop` branch. 
With the right version, it does work!

Thanks again!
